name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ 1.21 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y webp
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - name: Test
      run: go test -v .
